version: '3.8'

services:
  # React Frontend
  frontend:
    image: frontend-images:test
    container_name: cakeshop-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 